spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:ATM_DEV_DB/


  flyway:
    locations: classpath:db/migration
    table: schema_version
    placeholder-prefix: V
    sql-migration-suffixes: .sql
    enabled: true
    baseline-on-migrate: true


  h2:
    console:
      enabled: true
      settings:
        web-admin-password: sa
        web-allow-others: true



